import localFont from "next/font/local";
import "./globals.css";
import Address from "./components/Address/Address";
import Navbar from './components/Navbar/Navbar';
import Footer from './components/Footer/Footer';
import 'bootstrap/dist/css/bootstrap.min.css'
import Hero from './components/Hero/Hero';


export const metadata = {
  title: "Welcome Diagnostic & Medical Center",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        
      <Address />
        <Navbar />
        <Hero />
        {children} 
        <Footer />

        
      </body>
    </html>
  );
}
